const serviceSearchData = [
  // Basic
  { name:"Color Print",          cat:"Basic Printing",    link:"service-detail.html?s=color-print",         tags:"colour color printing photocopy document" },
  { name:"Photocopy",            cat:"Basic Printing",    link:"service-detail.html?s=photocopy",           tags:"copy xerox photocopy document" },
  { name:"Printout",             cat:"Basic Printing",    link:"service-detail.html?s=printout",            tags:"print printout bw black white" },
  { name:"Lamination",           cat:"Basic Printing",    link:"service-detail.html?s=lamination",          tags:"lamination protect plastic coat" },
  { name:"Online Form Photo",    cat:"Basic Printing",    link:"service-detail.html?s=form-photo-print",    tags:"form photo aadhaar pan passport size" },
  { name:"Passport Size Photo",  cat:"Basic Printing",    link:"service-detail.html?s=passport-size-photo", tags:"passport photo size studio instant" },
  { name:"Scanning",             cat:"Basic Printing",    link:"service-detail.html?s=scanning",            tags:"scan scanning pdf document" },
  // Computer
  { name:"Aadhaar Update",       cat:"Computer Services", link:"service-detail.html?s=aadhaar-update",      tags:"aadhaar aadhar update address name mobile" },
  { name:"PAN Card",             cat:"Computer Services", link:"service-detail.html?s=pan-card",            tags:"pan card new apply correction" },
  { name:"PC Repair",            cat:"Computer Services", link:"service-detail.html?s=pc-repair",           tags:"pc computer repair desktop fix" },
  { name:"Laptop Repair",        cat:"Computer Services", link:"service-detail.html?s=laptop-repair",       tags:"laptop repair screen battery keyboard" },
  { name:"Virus Removal",        cat:"Computer Services", link:"service-detail.html?s=virus-removal",       tags:"virus malware removal antivirus clean" },
  { name:"Windows Installation", cat:"Computer Services", link:"service-detail.html?s=windows-installation",tags:"windows install os format" },
  { name:"MS Office Installation",cat:"Computer Services",link:"service-detail.html?s=ms-office-installation",tags:"office word excel powerpoint install" },
  { name:"Software Installation", cat:"Computer Services",link:"service-detail.html?s=software-installation",tags:"software install setup" },
  { name:"Printer Setup",        cat:"Computer Services", link:"service-detail.html?s=printer-setup",       tags:"printer setup install wifi network" },
  { name:"Resume Creation",      cat:"Computer Services", link:"service-detail.html?s=resume-creation",     tags:"resume cv job create design" },
  { name:"Document Typing",      cat:"Computer Services", link:"service-detail.html?s=document-typing",     tags:"typing document letter hindi english" },
  { name:"Passport Assistance",  cat:"Computer Services", link:"service-detail.html?s=passport-assistance", tags:"passport apply renewal tatkal" },
  { name:"Online Bill Payment",  cat:"Computer Services", link:"service-detail.html?s=online-bill-payment", tags:"bill payment electricity water gas mobile" },
  { name:"Railway Ticket Booking",cat:"Computer Services",link:"service-detail.html?s=railway-ticket-booking",tags:"train railway irctc ticket booking tatkal" },
  { name:"Flight Booking",       cat:"Computer Services", link:"service-detail.html?s=flight-booking",      tags:"flight air ticket booking" },
  { name:"Govt. Form Submission", cat:"Computer Services",link:"service-detail.html?s=govt-form-submission", tags:"government form online portal submit" },
  { name:"Email Creation",       cat:"Computer Services", link:"service-detail.html?s=email-creation",      tags:"email gmail account create setup" },
  { name:"PDF Editing",          cat:"Computer Services", link:"service-detail.html?s=pdf-editing",         tags:"pdf edit merge split compress convert" },
  { name:"Image Editing",        cat:"Computer Services", link:"service-detail.html?s=image-editing",       tags:"photo edit background remove resize" },
  { name:"Data Entry",           cat:"Computer Services", link:"service-detail.html?s=data-entry",          tags:"data entry excel typing bulk" },
  { name:"Internet Browsing",    cat:"Computer Services", link:"service-detail.html?s=internet-browsing",   tags:"internet browsing research download" },
  // Visiting Cards
  { name:"Visiting Card",          cat:"Visiting Cards",  link:"service-detail.html?s=visiting-card",       tags:"visiting card business standard" },
  { name:"SBS Visiting Card",      cat:"Visiting Cards",  link:"service-detail.html?s=sbs-visiting-card",   tags:"sbs visiting card premium white" },
  { name:"Gloss Visiting Card",    cat:"Visiting Cards",  link:"service-detail.html?s=gloss-visiting-card", tags:"gloss shiny visiting card" },
  { name:"Matt Finish Visiting Card",cat:"Visiting Cards",link:"service-detail.html?s=matt-finish-visiting-card",tags:"matt matte finish visiting card" },
  { name:"Velvet Visiting Card",   cat:"Visiting Cards",  link:"service-detail.html?s=velvet-visiting-card",tags:"velvet soft touch visiting card luxury" },
  { name:"Premium Visiting Card",  cat:"Visiting Cards",  link:"service-detail.html?s=premium-visiting-card",tags:"premium thick 700gsm visiting card" },
  { name:"UV Visiting Card",       cat:"Visiting Cards",  link:"service-detail.html?s=uv-visiting-card",    tags:"uv spot visiting card raised glossy" },
  { name:"Gold/Silver Foil Card",  cat:"Visiting Cards",  link:"service-detail.html?s=gold-silver-foil-card",tags:"gold silver foil visiting card luxury" },
  { name:"MGI Visiting Card",      cat:"Visiting Cards",  link:"service-detail.html?s=mgi-visiting-card",   tags:"mgi 3d raised uv premium visiting card" },
  // Letterheads
  { name:"DO Paper Letterhead",    cat:"Letterheads",     link:"service-detail.html?s=do-paper-letterhead",  tags:"letterhead do paper standard" },
  { name:"Bond Paper Letterhead",  cat:"Letterheads",     link:"service-detail.html?s=bond-paper-letterhead",tags:"bond paper letterhead official" },
  { name:"Matt Finish Letterhead", cat:"Letterheads",     link:"service-detail.html?s=matt-finish-letterhead",tags:"matt matte letterhead premium" },
  { name:"Gold/Silver Leaf Letterhead",cat:"Letterheads", link:"service-detail.html?s=gold-silver-leaf-letterhead",tags:"gold silver foil letterhead" },
  { name:"Maplitho Letterhead",    cat:"Letterheads",     link:"service-detail.html?s=maplitho-letterhead",  tags:"maplitho letterhead natural" },
  // Stickers
  { name:"Gum Sheet Sticker",      cat:"Stickers",        link:"service-detail.html?s=gum-sheet-sticker",    tags:"sticker gum sheet label" },
  { name:"Vinyl Sheet Sticker",    cat:"Stickers",        link:"service-detail.html?s=vinyl-sheet-sticker",  tags:"vinyl sticker weatherproof outdoor" },
  { name:"Water Bottle Label",     cat:"Stickers",        link:"service-detail.html?s=water-bottle-label",   tags:"water bottle label waterproof" },
  { name:"Packaging Label",        cat:"Stickers",        link:"service-detail.html?s=packaging-label",      tags:"packaging label product box" },
  { name:"Gold/Silver Leaf Sticker",cat:"Stickers",       link:"service-detail.html?s=gold-silver-leaf-sticker",tags:"gold silver foil sticker premium" },
  { name:"UV Sticker",             cat:"Stickers",        link:"service-detail.html?s=uv-sticker",           tags:"uv gloss sticker raised" },
  // Large Format
  { name:"Flex Printing",          cat:"Large Format",    link:"service-detail.html?s=flex-printing",        tags:"flex banner printing outdoor" },
  { name:"Vinyl Printing",         cat:"Large Format",    link:"service-detail.html?s=vinyl-printing",       tags:"vinyl printing wall vehicle" },
  { name:"One Vision Printing",    cat:"Large Format",    link:"service-detail.html?s=one-vision-printing",  tags:"one vision window glass printing" },
  { name:"3D Letter Board",        cat:"Large Format",    link:"service-detail.html?s=3d-letter-board",      tags:"3d letter board signage" },
  { name:"Acrylic Letter Board",   cat:"Large Format",    link:"service-detail.html?s=acrylic-letter-board", tags:"acrylic letter board office" },
  { name:"Glow Shine Board",       cat:"Large Format",    link:"service-detail.html?s=glow-shine-board",     tags:"glow shine board backlit night" },
  { name:"Road Signage Board",     cat:"Large Format",    link:"service-detail.html?s=road-signage-board",   tags:"road sign board outdoor" },
  { name:"Retro Printing",         cat:"Large Format",    link:"service-detail.html?s=retro-printing",       tags:"retro vintage printing decor" },
  { name:"Sun Board Printing",     cat:"Large Format",    link:"service-detail.html?s=sun-board-printing",   tags:"sun board pvc indoor signage" },
  { name:"Neo Board",              cat:"Large Format",    link:"service-detail.html?s=neo-board",            tags:"neo board display premium signage" },
  { name:"Clip-on Board",          cat:"Large Format",    link:"service-detail.html?s=clipon-board",         tags:"clipon snap frame display board" },
  { name:"Canopy",                 cat:"Large Format",    link:"service-detail.html?s=canopy",               tags:"canopy tent event outdoor branded" },
  { name:"Roll Up Standee",        cat:"Large Format",    link:"service-detail.html?s=roll-up-standee",      tags:"roll up standee portable display" },
  // Books
  { name:"Brochure",               cat:"Books & Booklets",link:"service-detail.html?s=brochure",             tags:"brochure trifold bifold marketing" },
  { name:"Product Catalogue",      cat:"Books & Booklets",link:"service-detail.html?s=product-catalogue",    tags:"product catalogue catalog printing" },
  { name:"Diary Printing",         cat:"Books & Booklets",link:"service-detail.html?s=diary-printing",       tags:"diary printing corporate gift" },
  { name:"Magazine Printing",      cat:"Books & Booklets",link:"service-detail.html?s=magazine-printing",    tags:"magazine printing multi page" },
  { name:"Note Pad",               cat:"Books & Booklets",link:"service-detail.html?s=note-pad",             tags:"note pad notepad branded" },
  { name:"Leaflet",                cat:"Books & Booklets",link:"service-detail.html?s=leaflet",              tags:"leaflet flyer single sheet" },
  { name:"Pamphlet",               cat:"Books & Booklets",link:"service-detail.html?s=pamphlet",             tags:"pamphlet 170gsm colour print" },
  { name:"Certificate Printing",   cat:"Books & Booklets",link:"service-detail.html?s=certificate",          tags:"certificate printing premium" },
  // Gifting
  { name:"Trophy",                 cat:"Gifting",         link:"service-detail.html?s=trophy",               tags:"trophy award engraved event" },
  { name:"Memento",                cat:"Gifting",         link:"service-detail.html?s=memento",              tags:"memento farewell gift personalized" },
  { name:"Medal",                  cat:"Gifting",         link:"service-detail.html?s=medal",                tags:"medal sports event award" },
  { name:"T-Shirt Printing",       cat:"Gifting",         link:"service-detail.html?s=t-shirt-printing",     tags:"tshirt t-shirt printing custom logo" },
  { name:"Mug Printing",           cat:"Gifting",         link:"service-detail.html?s=mug-printing",         tags:"mug cup photo printing gift" },
  { name:"Pen Printing",           cat:"Gifting",         link:"service-detail.html?s=pen-printing",         tags:"pen printing logo corporate gift" },
  { name:"Customised Clock",       cat:"Gifting",         link:"service-detail.html?s=customised-clock",     tags:"clock photo custom gift" },
  { name:"Customised Bag",         cat:"Gifting",         link:"service-detail.html?s=customised-bag",       tags:"bag custom branded printing gift" },
  // Stationery
  { name:"Office Register",        cat:"Stationery",      link:"service-detail.html?s=office-register",      tags:"office register custom printing" },
  { name:"Office Stationery",      cat:"Stationery",      link:"service-detail.html?s=office-stationery",    tags:"office stationery letterhead envelope" },
  { name:"Envelope Printing",      cat:"Stationery",      link:"service-detail.html?s=envelope",             tags:"envelope printing branded" },
  { name:"Bill Book",              cat:"Stationery",      link:"service-detail.html?s=bill-book",            tags:"bill book ncr carbon copy invoice" },
  { name:"Form Printing",          cat:"Stationery",      link:"service-detail.html?s=form-printing",        tags:"form printing custom office" },
  { name:"Banking Stationery",     cat:"Stationery",      link:"service-detail.html?s=banking-stationery",   tags:"banking stationery forms deposit withdrawal" },
  { name:"Passbook",               cat:"Stationery",      link:"service-detail.html?s=passbook",             tags:"passbook bank printing custom" },
  // ID Cards
  { name:"ID Card",                cat:"ID Cards",        link:"service-detail.html?s=id-card",              tags:"id card pvc school office" },
  { name:"Lanyards",               cat:"ID Cards",        link:"service-detail.html?s=lanyards",             tags:"lanyard id card neck strap" },
  { name:"Acrylic ID Card",        cat:"ID Cards",        link:"service-detail.html?s=acrylic-id-card",      tags:"acrylic id card premium clear" },
  { name:"Acrylic Name Plate",     cat:"ID Cards",        link:"service-detail.html?s=acrylic-name-plate",   tags:"acrylic name plate desk door office" },
  { name:"Metal Badge",            cat:"ID Cards",        link:"service-detail.html?s=metal-badge",          tags:"metal badge engraved corporate" },
  // Wedding
  { name:"Digital Wedding Card",   cat:"Wedding Cards",   link:"service-detail.html?s=digital-wedding-card", tags:"digital wedding card whatsapp online" },
  { name:"Invitation Card",        cat:"Wedding Cards",   link:"service-detail.html?s=invitation-card",      tags:"invitation card event wedding birthday" },
  { name:"Traditional Wedding Card",cat:"Wedding Cards",  link:"service-detail.html?s=traditional-wedding-card",tags:"traditional wedding card print" },
  { name:"Thank You Card",         cat:"Wedding Cards",   link:"service-detail.html?s=thank-you-card",       tags:"thank you card wedding gift" },
  // DTF
  { name:"DTF Printing",           cat:"DTF Printing",    link:"service-detail.html?s=dtf-printing",         tags:"dtf direct film transfer tshirt fabric" },
  { name:"UV DTF Printing",        cat:"DTF Printing",    link:"service-detail.html?s=uv-dtf-printing",      tags:"uv dtf glass acrylic metal transfer" },
];